export const DEMO_ROLES = [
  {
    id: 'cs',
    email: 'cs@tourism.go.ke',
    password: 'password',
    name: 'Hon. James Kariuki Mwangi',
    title: 'Cabinet Secretary',
    department: 'Office of the Cabinet Secretary',
    emoji: '🦁',
    color: '#006B3C',
    tagline: 'Top-level authority',
    description: 'See everything. Approve major decisions. Review Ministry-wide reports and audit trails.',
    highlights: ['Final workflow approvals', 'Ministry-wide reports', 'Full audit log', 'All memos and documents'],
  },
  {
    id: 'hod_finance',
    email: 'director.finance@tourism.go.ke',
    password: 'password',
    name: 'Ms. Esther Wambui Kamau',
    title: 'Director, Finance & Administration',
    department: 'Directorate of Finance & Administration',
    emoji: '📋',
    color: '#0366D6',
    tagline: 'Department head',
    description: 'Approve procurement requests, manage your team\'s leave, track contracts, send department memos.',
    highlights: ['Workflow approvals', 'Leave management', 'Contract registry', 'Department memos'],
  },
  {
    id: 'ict_director',
    email: 'director.ict@tourism.go.ke',
    password: 'password',
    name: 'Mr. Samuel Njoroge Waweru',
    title: 'Director, ICT',
    department: 'Directorate of ICT',
    emoji: '💻',
    color: '#6F42C1',
    tagline: 'ICT lead',
    description: 'Manage asset disposal workflows, oversee the helpdesk queue, track Ministry ICT assets.',
    highlights: ['Asset disposal workflows', 'ICT helpdesk queue', 'Asset registry', 'Reports & audit'],
  },
  {
    id: 'ict_admin',
    email: 'dennis.kiprop@tourism.go.ke',
    password: 'password',
    name: 'Mr. Dennis Kiprop Sang',
    title: 'Senior Systems Administrator',
    department: 'Directorate of ICT',
    emoji: '⚙️',
    color: '#E36209',
    tagline: 'System Administrator',
    description: 'Create and manage staff accounts, configure roles and permissions, handle the helpdesk queue.',
    highlights: ['Staff account management', 'Role & permissions setup', 'ICT helpdesk queue', 'Org chart & directory'],
  },
  {
    id: 'staff',
    email: 'mary.achieng@tourism.go.ke',
    password: 'password',
    name: 'Ms. Mary Achieng Oluoch',
    title: 'Accountant',
    department: 'Directorate of Finance & Administration',
    emoji: '👩‍💼',
    color: '#28A745',
    tagline: 'General staff',
    description: 'The everyday experience — receiving memos, applying for leave, raising ICT support tickets.',
    highlights: ['Memo inbox & acknowledgment', 'Leave applications', 'ICT helpdesk', 'Notice board'],
  },
  {
    id: 'auditor',
    email: 'auditor@tourism.go.ke',
    password: 'password',
    name: 'Ms. Catherine Muthoni Kariuki',
    title: 'Internal Auditor',
    department: 'Directorate of Finance & Administration',
    emoji: '🔍',
    color: '#D73A49',
    tagline: 'Oversight & compliance',
    description: 'Read-only access to everything. Full audit trail, reports, and accountability across all directorates.',
    highlights: ['Full audit log', 'All reports', 'Memo acknowledgment rates', 'Workflow performance'],
  },
];
